In [55]:
import numpy as np
from numpy import mean
from numpy import std
import pandas as pd
import scipy
from scipy import stats #standardization
from sklearn import preprocessing #label encoder, max scaler
from sklearn.model_selection import train_test_split #train/validation 
from sklearn.linear_model import LogisticRegression
#import necessary utilities
print(".")

.


In [136]:
df = pd.read_csv(filepath_or_buffer='train.dat', header=0) #read the training data file
df2 = pd.read_csv(filepath_or_buffer='test.dat', header=0) #read the test data file

#preprocessing: manually removing redundant columns
#many columns are repeated/extraneous data that may hinder the prediction
df = df.drop(['CONTROLN'], axis=1)
df = df.drop(['FISTDATE'], axis=1)
df = df.drop(['NEXTDATE'], axis=1)
df = df.drop(['MAXRDATE'], axis=1)
df = df.drop(['MINRDATE'], axis=1)
df = df.drop(df.loc[:,'RDATE_3':'RDATE_24'].columns, axis=1)
df = df.drop(['MAXADATE'], axis=1)
df = df.drop(df.loc[:,'ADATE_2':'ADATE_24'].columns, axis=1)
df = df.drop(df.loc[:,'POP90C1':'AC2'].columns, axis=1)
df = df.drop(df.loc[:,'COLLECT1':'PLATES'].columns, axis=1)
df = df.drop(['GEOCODE'], axis=1)
df = df.drop(df.loc[:,'MALEMILI':'FEDGOV'].columns, axis=1)
df = df.drop(df.loc[:,'CHILD03':'CHILD18'].columns, axis=1)
df = df.drop(['AGEFLAG'], axis=1)
df = df.drop(['DOMAIN'], axis=1)
df = df.drop(['DOB'], axis=1)
df = df.drop(['ZIP'], axis=1)
df = df.drop(['OSOURCE'], axis=1)

df2 = df2.drop(['CONTROLN'], axis=1)
df2 = df2.drop(['FISTDATE'], axis=1)
df2 = df2.drop(['NEXTDATE'], axis=1)
df2 = df2.drop(['MAXRDATE'], axis=1)
df2 = df2.drop(['MINRDATE'], axis=1)
df2 = df2.drop(df2.loc[:,'RDATE_3':'RDATE_24'].columns, axis=1)
df2 = df2.drop(['MAXADATE'], axis=1)
df2 = df2.drop(df2.loc[:,'ADATE_2':'ADATE_24'].columns, axis=1)
df2 = df2.drop(df2.loc[:,'POP90C1':'AC2'].columns, axis=1)
df2 = df2.drop(df2.loc[:,'COLLECT1':'PLATES'].columns, axis=1)
df2 = df2.drop(['GEOCODE'], axis=1)
df2 = df2.drop(df2.loc[:,'MALEMILI':'FEDGOV'].columns, axis=1)
df2 = df2.drop(df2.loc[:,'CHILD03':'CHILD18'].columns, axis=1)
df2 = df2.drop(['AGEFLAG'], axis=1)
df2 = df2.drop(['DOMAIN'], axis=1)
df2 = df2.drop(['DOB'], axis=1)
df2 = df2.drop(['ZIP'], axis=1)
df2 = df2.drop(['OSOURCE'], axis=1)

df

C:\Users\alkal\AppData\Local\Temp\ipykernel_19204\3243125464.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath_or_buffer='train.dat', header=0) #read the training data file
C:\Users\alkal\AppData\Local\Temp\ipykernel_19204\3243125464.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(filepath_or_buffer='test.dat', header=0) #read the test data file


ODATEDW  TCODE STATE MAILCODE PVASTATE NOEXCH RECINHSE RECP3 RECPGVG  \
0         8901      0    AL                        0                          
1         9501      0    AL                        0                          
2         9301      0    TX                        0                          
3         9301     28    FL                        0                          
4         9401      0    CA                        0                          
...        ...    ...   ...      ...      ...    ...      ...   ...     ...   
76324     9601      1    NM                        0                          
76325     9501      1    FL                        0                          
76326     8801      1    AL                        0                          
76327     8601      1    CO                        0                          
76328     9001      3    IL                        0                          

      RECSWEEP  ... HPHONE_D RFA_2R  RFA_2F RFA_2A  MDMAUD_R  MDMAUD_F  \
0               ...        1      L       1      E         X         X   
1               ...        0      L       3      F         X         X   
2               ...        0      L       4      D         X         X   
3               ...        1      L       2      F         X         X   
4               ...        1      L       1      F         X         X   
...        ...  ...      ...    ...     ...    ...       ...       ...   
76324           ...        0      L       1      F         X         X   
76325           ...        1      L       1      G         X         X   
76326           ...        1      L       3      G         X         X   
76327           ...        1      L       1      E         X         X   
76328           ...        0      L       1      F         X         X   

      MDMAUD_A  CLUSTER2  GEOCODE2  TARGET  
0            X      51.0         B     0.0  
1            X      44.0         C     0.0  
2            X      19.0         B     0.0  
3            X      13.0         C     0.0  
4            X       3.0         A     0.0  
...        ...       ...       ...     ...  
76324        X      37.0         C     0.0  
76325        X      18.0         B     0.0  
76326        X      15.0         B    30.0  
76327        X      36.0         C     0.0  
76328        X      44.0         D     0.0  

[76329 rows x 111 columns]

In [138]:
#preprocessing, want to label encode some columns to normalize them in integer form
le = preprocessing.LabelEncoder()

#reset column names
df.columns = range(df.shape[1])
df2.columns = range(df2.shape[1])

#consider column as type string to avoid error of mixing floats and strings
for i in range(110):
    df[i] = le.fit_transform(df[i].astype(str))
    df2[i] = le.fit_transform(df2[i].astype(str))

#put columns in an output file
# with open("info.dat", "w") as fh:
#     for i in range(len(df.iloc[0])):
#         if(i==0):
#             continue
#         fh.write(str(df.iloc[0][i]))
#         fh.write('\n')

df

0    1    2    3    4    5    6    7    8    9    ...  101  102  103  \
0        7    0   23    0    0    1    0    0    0    0  ...    1    0    0   
1       37    0   23    0    0    1    0    0    0    0  ...    0    0    2   
2       28    0   43    0    0    1    0    0    0    0  ...    0    0    3   
3       28   18    5    0    0    1    0    0    0    0  ...    1    0    1   
4       33    0   55    0    0    1    0    0    0    0  ...    1    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
76324   43    1   31    0    0    1    0    0    0    0  ...    0    0    0   
76325   37    1    5    0    0    1    0    0    0    0  ...    1    0    0   
76326    5    1   23    0    0    1    0    0    0    0  ...    1    0    2   
76327   12    1   56    0    0    1    0    0    0    0  ...    1    0    0   
76328   11   20   11    0    0    1    0    0    0    0  ...    0    0    0   

       104  105  106  107  108  109   110  
0        1    4    3    4   41    2   0.0  
1        2    4    3    4   32    3   0.0  
2        0    4    3    4    2    2   0.0  
3        2    4    3    4   34    3   0.0  
4        2    4    3    4   15    1   0.0  
...    ...  ...  ...  ...  ...  ...   ...  
76324    2    4    3    4   24    3   0.0  
76325    3    4    3    4   62    2   0.0  
76326    3    4    3    4   56    2  30.0  
76327    1    4    3    4   22    3   0.0  
76328    2    4    3    4   32    4   0.0  

[76329 rows x 111 columns]

In [139]:
scaler = preprocessing.MaxAbsScaler()

#features and labels are numpy arrays containing sample attributes, and target variable rescpectively
features = df.iloc[:2000,:110].values
labels = df.iloc[:2000,110].values

features2 = df2.iloc[:,:110].values

print(features, len(features), len(features[0]))
#split up training dataset to train and validation set, with 80/20 ratio
X_train, X_valid, y_train, y_valid = train_test_split(features, labels, test_size=1)

print(X_train.shape, features2.shape)
print(X_train[0])
print(features2[0])
print(len(X_train), len(X_valid))

[[ 7  0 23 ...  4 41  2]
 [37  0 23 ...  4 32  3]
 [28  0 43 ...  4  2  2]
 ...
 [33  7  5 ...  4  0  1]
 [18 18 13 ...  4 32  4]
 [11  7 40 ...  4 18  2]] 2000 110
(1999, 110) (19083, 110)
[  18    0   31    0    0    1    0    0    0    0   20   38   94    0
    6    7    3    2    0    6    5    2    7    9    6    5    6    7
    2    9    2    3    2    0    0    0    0    6    0    0 8409  527
 1770    1   23   23    0   62    0    0   46    0   38   45    0    0
    0   68   52   55   53   23   36   50    0   23   34  157    5   12
   19   21    7   35   66   98   80   84   73    9   71   96   72   20
   69   98   72   61   71   85   69   70  237   30    4   41  226  168
   22   45 3924    0    0    0    2    4    3    4   49    4]
[   7    0   48    0    0    1    0    0    0    0    6   17   33    1
    7    5    1   10    6    1    0    5    0    0    0    0    0    2
    3    3    3    0    4    3    0    0    0    2    0    0 5050  242
 1264    1   23   23    0   44   34   

In [103]:
features[0][109], y_valid[0]

(2, 0.0)

In [132]:
#test model accuracy, report using root mean squared error
from sklearn.metrics import mean_squared_error

#evaluate
def evaluate(model):
    model.fit(X_train, y_train)

    #for analyzing the model on the validation set
    #prediction = model.predict(X_valid)
    #print(prediction, len(prediction), type(prediction))

    prediction = model.predict(features2)
    print(prediction, len(prediction), type(prediction))

    #put the predictions in the output file
    with open("output.dat", "w") as fh:
        for i in range(len(prediction)):
            fh.write(str(prediction[i]))
            fh.write('\n')

    #for validation purposes
    #scores = mean_squared_error(y_valid, prediction) #return model's root mean squared error on the test set
    #return scores

In [140]:
#want to do singular value decomposition
#should perform well with the sparse dataset
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

# define the pipeline
#after evaluation n_components=10 yielded the best result
# for i in range(1,20):
#     print(i*5)
#     steps = [('scaler', StandardScaler()), ('svd', TruncatedSVD(n_components=i*5)), ('m', LogisticRegression(max_iter=20000))]
#     svd = Pipeline(steps=steps)
#     scores = evaluate(svd)
#     print('root mean squared error: ', scores)

steps = [('svd', TruncatedSVD(n_components=10)), ('m', LogisticRegression(max_iter=50000))]
#steps = [('scaler', StandardScaler()), ('svd', TruncatedSVD(n_components=40)), ('m', LogisticRegression(max_iter=20000))]
svd = Pipeline(steps=steps)
scores = evaluate(svd)
print('root mean squared error: ', scores)

#print out the validation
#print(y_valid, len(y_valid), type(y_valid))

[0. 0. 0. ... 0. 0. 0.] 19083 <class 'numpy.ndarray'>
root mean squared error:  None


c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [139]:
#want to do singular value decomposition
#should perform well with the sparse dataset
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# define the pipeline
for i in range(1,20):
    print(i*5)
    steps = [('scaler', StandardScaler(with_mean=False)), ('svd', TruncatedSVD(n_components=i*5)), ('m', LogisticRegression(max_iter=20000))]
    svd = Pipeline(steps=steps)
    scores = evaluate(svd)
    print('root mean squared error: ', scores)

print(y_valid, len(y_valid), type(y_valid))

5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [138]:
#knn
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.pipeline import Pipeline

# # define the pipeline
# steps = [('scaler', StandardScaler(with_mean=False)), ('knn', KNeighborsClassifier(n_neighbors=2))]
# knn = Pipeline(steps=steps)

# scores = evaluate(knn)
# print('root mean squared error: ', scores)

# print(y_valid, len(y_valid), type(y_valid))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.